// Generated by grunt: browserify-imports
(function moduleInit_dmcLandingpage() {
	'use strict';

	// Add require for other modules here
	// require('../my.other.module');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./confirm-order');
	require('./confirmation-page');
	require('./index-page');
	require('./landing-page');
	require('./main-panel');
	require('./sorry-page');
	var modules = ["dmc.debitcardapp.confirmOrder","dmc.debitcardapp.confirmationPage","dmc.debitcardapp.indexPage","dmc.debitcardapp.landingPage","dmc.debitcardapp.mainPanel","dmc.debitcardapp.sorryPage"];
	// EndRequire

	// Add your angular module dependencies here
	// modules.push('my.other.module');

	angular.module('dmc.debitcardapp', modules);
})();
